apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreleasenginx
  Ilabels:
   app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            
          readinessProbe:
            
          resources:
           requests:
            cpu: 100m
            memory: 128Mi
           limits:
            cpu: 100m
            memory: 128Mi
          volumeMounts:
           - name: nginx-volume
             mountPath: "/usr/share/nginx/html"
      volumes:
       - name: nginx-volume
         persistentVolumeClaim:
          claimName: nginx-vpc  
      nodeSelector:
       role: worker
