apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-chart.fullname" . }}-pvc
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join ", " }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
